apiVersion: v1
kind: Service
metadata:
  name: hlk-service
  namespace: elastic-system
spec:
  type: NodePort
  selector:
    app: hlk  # 修正: ラベルセレクターを 'app: hlk' に変更
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hlk-daemonset
  labels:
    app: hlk  # 修正: 一貫性のあるラベル 'app: hlk' を使用
spec:
  selector:
    matchLabels:
      app: hlk  # 修正: 一貫性のあるラベルセレクター 'app: hlk' を使用
  template:
    metadata:
      labels:
        app: hlk  # 修正: 一貫性のあるラベル 'app: hlk' を使用
    spec:
      containers:
      - name: hlk-container
        image: tororomeshi/hlk:latest
        ports:
        - containerPort: 8080
        # hostPort の設定は必要に応じて調整
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/containers
          type: Directory

