name: Python Code Quality and Lint

on: [push]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black isort requests

    - name: Format Python code with isort
      run: isort .

    - name: Format Python code with black
      run: black .

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated code formatting" -a || echo "No changes to commit"
        git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        git push


    - name: Analyse code with Pylint
      run: pylint $(git ls-files '*.py')
